### ISSUE TITLE
API Usability

### ISSUE THREAD

**Issue by Informatic** [opendata-stuttgart/feinstaub-api#12]
Hey!
Is there any official API documentation?

Right now API seems rather... unpleasant at best. Here are my thoughts:

* [ ] Add filtering to `/api/v1/now/` (mostly by country code, maybe by lat/lon + average radius) - right now it takes about 2.5min to generate this view, maybe some caching would be a sensible option as well?
* [ ] Find a way of accessing related sensors (right now I am only able to find sensor ID of my SDS011 by looking at maps.luftdaten.info, but not the node ID, which would give me a look into both SDS011 and DHT22 values) - even returning node_id in `/api/v1/sensor/.../` response would be enough

**Comment by ricki-z** [comment]
Please look at the documentation at:
https://github.com/opendata-stuttgart/meta/wiki/APIs
There you will find a possibility to filter by country, sensor type, geo position (box, circle).
And there is a endpoint for the data of a single sensor.
Some parts of the documentation ar in german only but some parts are also translated in english.

**Comment by ricki-z** [comment]
And: there shouldn't be a public access to the API beside the endpoint /push-sensor-data/ . We create the data JSON files once per minute. So there is some kind of caching.

**Comment by Informatic** [comment]
Ah. This makes a lot of sense now. `/api/v1/filter` is exactly what I needed.

Where is it implemented? I can't find it in this repository.

Can we make https://api.luftdaten.info redirect to some informational page about API? (even this wiki page would work) DRF explorer running over there is pretty useless right now.

**Comment by ricki-z** [comment]
This is implemented in PHP. I will push it to github in the near future. We needed to optimize some requests. The Django API needs too much resources on this, but is fast at receiving data.

**Comment by Informatic** [comment]
There are definitely some things to optimize in that django service. I'll try to take a look into it in my spare time.
