### ISSUE TITLE
Home Assistant User Agents are getting blocked - Unable to query own data

### ISSUE THREAD

**Issue by jensihnow** [opendata-stuttgart/feinstaub-api#13]
Hi Luftdaten project tema,

unfortunately the Home Assistant user agents are getting blocked 403 on the API.

>It looks like the webserver is blocking specific HA version strings (0.84.3 through 0.84.6)

This is also surprising as the project is listing Home Assistant as an official client/plugin on https://luftdaten.info/faq/#toggle-id-8

Please also see the issue on the Home Assistant project https://github.com/home-assistant/home-assistant/issues/19622

Do you experienced any issues with the Home Assistant plugin which need to be fixed?

Thanks

**Comment by ricki-z** [comment]
Some of the HomeAssistant clients are requesting the same data dozens of times in a short amount of time. So only a small amount of these clients is creating more requests than all the other clients. Thats why we are blocking versions 0.84.x.

**Comment by iliyan-s-petkov** [comment]
That is a valid reason to try to restrict the request rate in a short term, but perhaps there are more optimal ways to throttle or block individual offenders instead.

**Comment by ricki-z** [comment]
These are NOT individual offenders. Its a known bug oft the Luftdaten plugin used with newer versions oft HomeAssistant. The plugin is creating new sensor instances on every new start of the HomeAssistant server.
So its an offensive software version we are blocking.

**Comment by iliyan-s-petkov** [comment]
I understand. Thanks.

**Comment by jensihnow** [comment]
Hi,

if this is a known bug do you have the reference for the fix?

Is the bug in the Home Assistant component (https://github.com/home-assistant/home-assistant/tree/dev/homeassistant/components/luftdaten) or the wrappen lib (https://github.com/fabaff/python-luftdaten)?

I wonder if it actually is being fixed or not and the next version will be delivered with the same exact issue.

**Comment by ricki-z** [comment]
A simple Google search for "homeassistant luftdaten creating new instances" shows the thread as the first result: https://github.com/home-assistant/home-assistant/issues/18838

**Comment by jvanderneutstulen** [comment]
> These are NOT individual offenders. Its a known bug oft the Luftdaten plugin used with newer versions oft HomeAssistant. The plugin is creating new sensor instances on every new start of the HomeAssistant server.
> So its an offensive software version we are blocking.

@ricki-z This is fixed in HA 0.87

**Comment by jensihnow** [comment]
Fix is documented on https://github.com/home-assistant/home-assistant/pull/20226
