### ISSUE TITLE
archive.luftdaten.info: Timestamp in UTC oder UTC+1/MEZ?

### ISSUE THREAD

**Issue by tordah** [opendata-stuttgart/feinstaub-api#25]
Moin,
da ich dazu bisher keine Infos finden konnte: Wurden die timestamp-Einträge in den csv-Dateien auf archive.luftdaten.info auf MEZ-Werte geändert bzw. auf ihre entsprechenden Zeitzone korrigiert, oder sind diese wie die timestamps in den JSON-Uploads auf data.sensor.community im UTC-Format? 
Betrachte ich die Werte für Silvester 19/20 als Referenz, sprechen die Höchstwerte meiner Sensoren um 00:00 Uhr für eine Korrektur auf MEZ, aber ich würde mich diesbezüglich gerne vergewissern.
Cheers!

**Comment by ricki-z** [comment]
The timestamps are in UTC.
